package com.demo.common.model;

import com.demo.common.model.base.BaseHost;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Host extends BaseHost<Host> {
	public static final Host dao = new Host();
	
	public Page<Host> paginate(int pageNumber, int pageSize,String hostIp,String hostName) {
		String whereSql ="";
		if(hostIp!=null&&hostIp.length()>0){
			whereSql+=" and hostIp ='"+hostIp+"'";
		}
		if(hostName!=null&&hostName.length()>0){
			whereSql+=" and hostName ='"+hostName+"'";
		}
		return paginate(pageNumber, pageSize, "select * from host where 1=1 "+whereSql+"order by hostIp asc");
	}
}
