package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePingrecord<M extends BasePingrecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setHostIp(java.lang.String hostIp) {
		set("hostIp", hostIp);
	}

	public java.lang.String getHostIp() {
		return get("hostIp");
	}

	public void setHostName(java.lang.String hostName) {
		set("hostName", hostName);
	}

	public java.lang.String getHostName() {
		return get("hostName");
	}

	public void setFirstPingTs(java.util.Date firstPingTs) {
		set("firstPingTs", firstPingTs);
	}

	public java.util.Date getFirstPingTs() {
		return get("firstPingTs");
	}

	public void setLastPingTs(java.util.Date lastPingTs) {
		set("lastPingTs", lastPingTs);
	}

	public java.util.Date getLastPingTs() {
		return get("lastPingTs");
	}

	public void setDownTime(java.lang.Double downTime) {
		set("downTime", downTime);
	}

	public java.lang.Double getDownTime() {
		return get("downTime");
	}

}
