package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHost<M extends BaseHost<M>> extends Model<M> implements IBean {

	public void setHostIp(java.lang.String hostIp) {
		set("hostIp", hostIp);
	}

	public java.lang.String getHostIp() {
		return get("hostIp");
	}

	public void setHostName(java.lang.String hostName) {
		set("hostName", hostName);
	}

	public java.lang.String getHostName() {
		return get("hostName");
	}

	public void setHostStatus(java.lang.String hostStatus) {
		set("hostStatus", hostStatus);
	}

	public java.lang.String getHostStatus() {
		return get("hostStatus");
	}

	public void setPingFlag(java.lang.String pingFlag) {
		set("pingFlag", pingFlag);
	}

	public java.lang.String getPingFlag() {
		return get("pingFlag");
	}

	public void setLastDownId(java.lang.String lastDownId) {
		set("lastDownId", lastDownId);
	}

	public java.lang.String getLastDownId() {
		return get("lastDownId");
	}

}
